In [89]:
import numpy as np
import math

# matrix multiplicates vector
def mxv(A, b):
    x = np.array([np.sum(A[i] * b) for i in range(len(A))])
    return x

# Gaussian elimination
def gausselm(A, b):
    B = np.copy(A)
    c = np.copy(b)
    for i in range(1, len(b)):
        t = B[i][i - 1] / B[i - 1][i - 1]
        B[i] -= B[i - 1] * t
        c[i] -= c[i - 1] * t
    return B, c

# backward substitution
def bsub(B, c):
    n = len(c)
    x = np.zeros(n)
    x[n - 1] = c[n - 1] / B[n - 1][n - 1]
    for j in range(n - 2, -1, -1):
        x[j] = c[j]
        for k in range(j + 1, n):
            x[j] -= x[k] * B[j][k]
        x[j] /= B[j][j]
    return x

# construct a matrix using vector a, b, c
def matrix(a, b, c):
    n = len(b)
    res = np.zeros([n, n])
    for i in range (0, n):
        for j in range(0, n):
            if i == j - 1:
                res[i][j] = c[j - 1]
            elif i == j:
                res[i][j] = b[j]
            elif i == j + 1:
                res[i][j] = a[j]
    return res

# solve matrix equation
def solv(a, b, c, r):
    A = matrix(a, b, c)
    B, d = gausselm(A, r)
    sol = bsub(B, d)
    return sol

n = 10
a = -1 * np.ones(n - 1)
b = 2 * np.ones(n)
c = -1 * np.ones(n - 1)
A = matrix(a, b, c)
print(A)
r = 0.1 * np.ones(n)
print ("r = ", r)
x = solv(a, b, c, r)
print ("solution = ", x)
r2 = mxv(A, x)
print("A * solution = ", r2)

# the results is right what we expected

[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]
r =  [ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]
solution =  [ 0.5  0.9  1.2  1.4  1.5  1.5  1.4  1.2  0.9  0.5]
A * solution =  [ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]
