In [31]:
import math
import numpy as np

def mxv(A, v):
    res = np.array([np.sum(A[i] * v) for i in range(len(A))])
    return res
    
def norm(v):
    return math.sqrt(np.sum(v[i]**2 for i in range(len(v))))

# outer product
def vxw(v, w):
    n = len(v)
    res = np.zeros([n, n])
    for i in range(0, n):
        for j in range(0, n):
            res[i][j] = v[i] * w[j]
    return res

# innen product
def axb(a, b):
    return np.sum(a[i] * b[i] for i in range(len(a)))

s = np.array([1, 2, 3])
t = vxw(np.array([1, 2, 3]), np.array([1, 2, 1]))
print(t)
print(s - s)

# suppose A is a nxn matrix
def tred2(A):
    x = np.array([A[i][0] for i in range(len(A))])
    e1 = np.zeros(len(x))
    e1[0] = 1
    u = x + norm(x) * e1
    p = 2 * mxv(A, u) / norm(u)**2
    pu= vxw(p, u)
    #AP = np.array([A[i] - pu[i] for i in range(len(A))])
    k = axb(u, p) / norm(u)**2
    b = p - k * u
    bu = vxw(b, u) + vxw(u, b)
    Aprime = np.array([A[i] - bu[i] for i in range(len(A))]) 
    return Aprime

print(tred2(t))
    

[[ 1.  2.  1.]
 [ 2.  4.  2.]
 [ 3.  6.  3.]]
[0 0 0]
[[ 9.60356745  0.67637424 -0.98543864]
 [ 0.67637424  1.35274848 -1.97087729]
 [ 1.01456136  2.02912271 -2.95631593]]
