Aufgabe 5.1

In [2]:
import numpy as np

x_0 = 4.0

# iteration 1
def verfahren1(x_0,itmax):
    x = x_0
    for i in range(itmax):
        dx = np.sin(x)
        x = x + dx
        print(x)
        if (abs(x - np.pi)< 1E-6 ):
            break
    return(x)    

def verfahren2(x_0,itmax):
    #
    x = x_0
    for i in range(itmax):
        dx = np.sin(x)/np.cos(x)
        x = x - dx
        print(x)
        if (abs(x - np.pi)< 1E-6 ):
            break
    return(x)    


verfahren1(x_0,10)
print('leer')
verfahren2(x_0,10)



def verfahren3(f,a,b, itmax):
    
    for i in range(itmax):
        
        x = 0.5*(a+b)
        if (f(a)*f(x) < 0):
            b = x
        else:
            a = x
        if (abs(x - np.pi)< 1E-6 ):
            break
        print(x)
    return(x,i)
print('irgendwtwas')
verfahren3(np.sin,2,4,100)   
#np.cos(np.pi)

3.24319750469
3.14176738376
3.14159265359
leer
2.84217871765
3.15087293969
3.14159238716
irgendwtwas
3.0
3.5
3.25
3.125
3.1875
3.15625
3.140625
3.1484375
3.14453125
3.142578125
3.1416015625
3.14111328125
3.141357421875
3.1414794921875
3.14154052734375
3.141571044921875
3.1415863037109375
3.1415939331054688
3.141590118408203


(3.141592025756836, 19)

## Aufgabe

$f(x)=sin(x)$

$x_t = x_{t-1} + f(x_{t-1})$

Wir definieren die Kontraktionsabbildung $g$

$g(x) = x + f(x)$

Wir setzen für f ein

$g(x)=x+sin(x)$

also

$g'(x) = 1 + cos(x)$

In der Nullstelle $\pi$ gilt $cos(\pi)=-1$ also $g'(\pi)=0$. Also haben wir in dieser Nullstelle quadratische Konvergenz genau wie beim Newtonverfahren.

Wir wissen, dass wir beim Newtonverfahren quadratische Konvergenz haben, rechnen, das aus Spaß an der Freude aber trotzdem nach.

Die Iteration lautet

$x_t= x_{t-1} - \frac{f(x_{t-1})}{f'(x_{t-1})}$

Nun $g(x) = x - sin(x)/cos(x)$

$g'(x)=1 - \frac{cos^2(x) +sin^2(x) }{cos^2(x)}$

$sin(\pi) = 0$ und damit $g'(\pi)=0$

## Aufgabe

Was macht der folgende code?

In [9]:
import numpy as np
import numpy.linalg as la

def klausurfunktion(p, Matrix, vektor):
    # p ist vektor von integern
    # vektor is eine Matrix oder ein Vektor
    n = Matrix.shape[0] # n ist anzahl der Zeilen
    # kommentar
    y = vektor[p,:]   #vertausche Zeilen von vektor, nach Reihenfolge in p
    # löse Ly = Pb 
    for i in range(1, n):
        y[i,:] -= Matrix[i,:i].dot(y[:i,:])
    # löse Rx = y
    x = y
    for i in range(n-1, -1, -1):
        x[i,:] -= Matrix[i,i+1:].dot(x[i+1:,:])
        x[i,:] /= Matrix[i,i]
    return x


In [13]:
def klausurfunktion2(A):
    n = A.shape[0]
    p = list(range(n))
    for k in range(n-1):
        # column pivoting
        pj = k + np.argmax(abs(A[k:,k])) # finde pivot element
        p[k], p[pj] = p[pj], p[k] # 
        A[[k,pj],:] = A[[pj,k],:]
        # eliminate
        A[k+1:,k] *= 1 / A[k,k]
        for j in range(k+1, n):
            A[j,k+1:] -= A[j,k] * A[k,k+1:]
    return p


A= np.array([[5,4,6],[15,14,18],[35,36,51]],dtype = float)
A_copy = A.copy()

b=np.array([1,1,1],dtype = float).reshape((3,1))
print(A)


p = klausurfunktion2(A)
print(A)

x = klausurfunktion(p,A,b)
print(x)
print(np.dot(A_copy,x))

[[  5.   4.   6.]
 [ 15.  14.  18.]
 [ 35.  36.  51.]]
[[ 35.          36.          51.        ]
 [  0.42857143  -1.42857143  -3.85714286]
 [  0.14285714   0.8          1.8       ]]
[[ 0.73333333]
 [-1.        ]
 [ 0.22222222]]
[[ 1.]
 [ 1.]
 [ 1.]]


## Aufgabe

Was macht der folgende Code


In [14]:
import numpy as np
# A ist nxn Matrix
def klausurfuntion3(A):

    R = np.zeros((A.shape[1], A.shape[1]))
    Q = np.zeros(A.shape)
    for k in range(0, A.shape[1]):
        R[k, k] = np.sqrt(np.dot(A[:, k], A[:, k]))   # berechne 2 Norm der k-ten Spalte
        Q[:, k] = A[:, k]/R[k, k] # schreibe normierte k-te Spalte in Q
        for j in range(k+1, A.shape[1]):
            R[k, j] = np.dot(Q[:, k], A[:, j])
            A[:, j] = A[:, j] - R[k, j]*Q[:, k]
    return Q, R

## Lösung



Die Funktion berechnet die QR Zerlegung von A mit Gram Schmidt.

Es gilt für die Spaltenvektoren von Q

$$q_1 = \frac{a_1}{\|a_1\|} $$

Für k=2,...,n
$$ \tilde{q}_k = a_k - \sum_{i=1}^{k-1} (a_k,q_i)_2 q_i, \ \ \ q_k = \frac{\tilde{q}_k}{\|\tilde{q}_k\|_2} $$


Das ist der Gram-Schmidt Teil.

Für die Einträge $r_{i,j}$ der Matrix R  gilt

$$r_{kk} = \|\tilde{q}_k\|_2 $$
und
$$ r_{ik} = (a_k,q_i)_2$$
sowie
$r_{ik} = 0$ für $i >k$.


Warum sollte man diesen Algorithmus eigentlich nicht verwenden?

Antwort: Aufgrund von Rundungsfehlern geht die orthongonalität in den Spalten von Q schnell verloren.

Besser ist das Householder Verfahren.