In [19]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.polynomial.legendre as leg

# a)
def eval_legendre(n, x):
    res = np.zeros(2)
    if n == 0:
        res[0] = 1
    else:
        L0 = 1
        L0abl = 0
        L1 = x
        L1abl = 1
        res[0] = x
        res[1] = 1
        for i in range(1, n):
            res[0] = ((2 * i + 1) * x * L1 - i * L0) / (i + 1)     # Ln(x)
            res[1] = (2 * i + 1) * (L1 + x * L1abl) - i * L0abl    # Ln'(x)
            L0 = L1
            L1 = res[0]
            L0abl = L1abl
            L1abl = res[1]
    return res

# test
a = eval_legendre(3, 2)
print(a)

[  17.   145.5]


In [32]:
# b)
def newton_leg(n, x, xi, itmax = 100, tol = 1e-15):
    res = 0              # result
    loop = -1            # Anzahl der Iterationen
    prod = 1             # Produkt von (x - ksi_i)
    summe = 0            # Summe von 1 / (x - ksi_i)
    for i in xi:
        prod *= x - i
        summe += 1 / (x - i)
    while 1:
        loop += 1
        Ln = eval_legendre(n, x)
        if abs(Ln[0]) <= tol * abs(Ln[1] * x) or abs(Ln[0]) <= tol:        # Abbruchkriterium
            if loop > itmax:
                print('Mehl als itmax!')
            return x
        p = Ln[0] / prod                                                  # p(x)
        pprime = Ln[1] / prod - Ln[0] * summe / prod                      # p'(x)
        x -= p / (pprime - p * summe)                                     # new x

In [100]:
# c)
def legroots_newton(n):
    ksi =np.array([])
    xi = newton_leg(n, 1, ksi)
    ksi = np.append(ksi, xi)
    xi = newton_leg(n, 2 * xi - 1, ksi)
    ksi = np.append(ksi, xi)
    for i in range(n // 2 - 2):
        xi = newton_leg(n, ksi[len(ksi) - 1] * 2 - ksi[len(ksi) - 2], ksi)
        ksi = np.append(ksi, xi)
    ksi = np.append(ksi, -1 * ksi)
    return ksi

In [102]:
# d)
print(legroots_newton(4))
print(legroots_newton(5))

Mehl als itmax!
Mehl als itmax!
[ 0.86113631  0.86113631 -0.86113631 -0.86113631]
Mehl als itmax!
Mehl als itmax!
[ 0.90617985  0.90617985 -0.90617985 -0.90617985]


In [103]:
# e)
N = np.array([21, 51, 101, 201, 501, 1001])
for n in N:
    print('n = ', n)
    nullstellen = legroots_newton(n)
    plt.plot(nullstellen)
    print ('Maximum: ', max(abs(i for i in nullstellen)))
    

n =  21


D:\Anaconda\lib\site-packages\ipykernel\__main__.py:9: RuntimeWarning: divide by zero encountered in double_scalars


TypeError: bad operand type for abs(): 'generator'

In [104]:
# f)
N = np.array([4])
for n in N:
    a = np.zeros(n + 1)
    a[n] = 1
    print(leg.legroots(a))

[-0.86113631 -0.33998104  0.33998104  0.86113631]
